### ISSUE TITLE
Windows, NodeJs 12 error: RangeError [ERR_UNKNOWN_MODULE_FORMAT]: Unknown module format: esm

### ISSUE THREAD

**Issue by xR3b0rn** [pongstylin/tactics#40]
Reproduce:
After
```
git clone ...
npm config set script-shell "C:\Program Files\Git\bin\bash.exe"
cd tactics
npm install
npm start
```
I'm running into this error msg:
```
λ npm start

> tactics@0.2.6 start C:\hij\github\tactics
> NODE_ENV=development webpack --watch --progress --hide-modules & node --experimental-modules --loader ./resolver.mjs --require dotenv/config src/server.js || true

(node:13796) ExperimentalWarning: The ESM module loader is experimental.
(node:13796) ExperimentalWarning: --loader is an experimental feature. This feature could change at any time
internal/modules/cjs/loader.js:830
      internalBinding('task_queue').triggerFatalException(
                                    ^

RangeError [ERR_UNKNOWN_MODULE_FORMAT]: Unknown module format: esm
    at Loader.getModuleJob (internal/modules/esm/loader.js:163:15)
    at async Loader.import (internal/modules/esm/loader.js:127:17)

C:\hij\github\tactics (master -> origin) (tactics@0.2.6)
λ  10% building 0/0 modules 0 active
webpack is watching the files…

Hash: b3a08d73a6508f84301d
Version: webpack 4.33.0
Time: 6046ms
Built at: 2019-06-10 13:39:03
             Asset      Size       Chunks                    Chunk Names
  chaos-app.min.js  25.8 KiB    chaos-app  [emitted]         chaos-app
classic-app.min.js  26.2 KiB  classic-app  [emitted]         classic-app
 createGame.min.js   184 KiB   createGame  [emitted]         createGame
faceoff-app.min.js  25.4 KiB  faceoff-app  [emitted]         faceoff-app
   game-app.min.js  36.4 KiB     game-app  [emitted]         game-app
    tactics.min.js  4.96 MiB      tactics  [emitted]  [big]  tactics
         ww.min.js   830 KiB           ww  [emitted]  [big]  ww
Entrypoint tactics [big] = tactics.min.js
Entrypoint faceoff-app = faceoff-app.min.js
Entrypoint chaos-app = chaos-app.min.js
Entrypoint classic-app = classic-app.min.js
Entrypoint game-app = game-app.min.js
Entrypoint ww [big] = ww.min.js
Entrypoint createGame = createGame.min.js
```

**Comment by xR3b0rn** [comment]
Workarround: Use NodeJS 10.

**Comment by pongstylin** [comment]
I committed a fix to the "nodeV12" branch.  I am not quite ready to move deployed environments to Node V12, so I'm not merging it into the master branch yet.  In the meantime, I'm resolving this issue since anybody who wishes to use Node V12 may do so by merging the nodeV12 branch into your fork.
